name: Release

on:
  push:
    branches: [ "develop" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:

    name: 🏗️ Release TurnipTales Libraries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew shadowJar --full-stacktrace

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: turniptales-libraries
          path: build/libs/turniptales-libraries.jar